### ISSUE TITLE
{ "presets" : ["es2015", "react"] }

### ISSUE THREAD

**Issue by codervince** [PacktPublishing/Mastering-Full-Stack-React-Web-Development#1]
Ran node server/index.js at bottom of page "A summary of how to run the project" 
Using node v4.0.0 (npm v2.14.2)
Got
module.js:471
    throw err;
    ^
Error: Cannot find module '../../modules/_core'

**Comment by AurobindoKar** [comment]
Hi,

I am closing the issue.
In case the issue still persists, feel free to reopen it.

Thanks
