### ISSUE TITLE
npm run dev return Path must be a string - 32 page

### ISSUE THREAD

**Issue by baeron** [PacktPublishing/Mastering-Full-Stack-React-Web-Development#2]
ERROR in ./src/app.js
Module build failed: TypeError: Path must be a string. Received undefined at assertPath (path.js:7:11)

**app.js**
`import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import article from './reducers/article';
import PublishingApp from './layouts/PublishingApp';

let store = createStore(article);

render(
  <Provider store={store}>
    <PublishingApp />
  </Provider>, document.getElementById('publishingAppRoot')
);`

package.json
`{
  "name": "react_full_stack",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "dev": "webpack-dev-server"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.15.0",
    "cors": "^2.7.1",
    "express": "^4.13.4",
    "mongoose": "^4.4.5",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.6.5",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.6.1",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "webpack": "^1.12.14",
    "webpack-dev-server": "^1.14.1"
  }
}`

What is the problem?

**Comment by baeron** [comment]
I do not know why, but now everything works.

**Comment by MurtazaTinwala** [comment]
Closed
